# Site settings
title: Vitali lobanov
header-img: img/home-bg.jpg
email: ithebfxy@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: /another-blog
url: http://lobanov.tech
twitter_username: powetoya
github_username:  bfxy
facebook_username:  vitali.lobanov

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
