# Site settings
title: Vitali Lobanov
header-img: img/lamp.jpg
email: ithebfxy@gmail.com
description: "Hey there! The site is under construction. Sorreh."
baseurl: /clean-blog
url: http://lobanov.tech
twitter_username: powetoya
github_username:  bfxy
facebook_username:  vitali.lobanov

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
